// Заглушка лора для релиза (Версия 0.9.5)
const encrypted_lore = [
    // ERROR_404: DATA CORRUPTED
    "eyJpZCI6ICJFUlJPUl80MDQiLCAidGl0bGUiOiAiREFUQSBDT1JSVVBURUQiLCAiY29udGVudCI6ICIhIEZBVEFMIEVSUk9SXG4hIERFQ1JZUFRJT04gRkFJTEVEXG4+IFRoZSBkYXRhIG9uIHRoaXMgZHJpdmUgaGFzIGJlZW4gcHVyZ2VkIGJ5IFZhbmd1YXJkIENvbW1hbmQuXG5bU1RBTVA6IERFTklFRF0ifQ=="
];
let lore_chapters = [];