const loreChapters = [
    {
        id: "DRIVE-01_FOUNDATION",
        title: "The Birth of the Commonwealth",
        content: "RECORDING INDEX: TBCW-HIST-001 // SECURE DRIVE STATUS: DECRYPTED.\n\nIn the beginning, there was no 'Commonwealth'. There were only the cold, unyielding teeth of the City's Wings and the frantic, bleeding scrambles of the Backstreets' lower depths. Following the collapse of Lobotomy Corporation and the subsequent chaotic 'White Nights and Black Days', an unprecedented power vacuum manifested across the southern districts.\n\nOur office was forged from the remnants of broken corporate security teams, stray Grade 2 Fixers, and survivors who had crawled out of Nest expulsions. We realized a singular, absolute truth: a lone Office is merely a snack for a Syndicate, and a Syndicate is merely an asset for a Wing. To survive, the Backstreets required a unified front — an invisible country hidden within the shadows of the Nests.\n\nThe foundation was laid in blood near District 12. We refused to pay protection taxes to the Finger-affiliated sub-syndicates, triggering a localized war that lasted forty-two days. By utilizing tactical guerilla architecture and building reinforced redoubts disguised as industrial factories, we bled them dry. The Commonwealth was born not out of political ambition, but as an existential reflex against the absolute tyranny of the Eye, the Claw, and the Brain."
    },
    {
        id: "DRIVE-02_NEIN_INCIDENT",
        title: "The NEIN Extraction Contract",
        content: "LOG CLASSIFICATION: CLASS-A INCD-774 // CODENAME: NEIN // RECOVERY: SUCCESS.\n\nThree years after our inception, Vanguard Command intercepted a high-frequency distress beacon bouncing off an abandoned sub-facility in District 4. The signature belonged to a deep-level research laboratory that had theoretically been 'liquidated' during L Corp's fall. The contract didn't come from the Hana Association; it was pushed to us anonymously through an untraceable black-market proxy.\n\nUpon extraction breach, Squad Gamma discovered that the facility was not empty. It was heavily populated by automated containment carapaces that had gone feral, alongside early-stage Distortions attempting to form a rudimentary hive mind around a fractured Singularity engine. The target of our extraction was a Singularity prototype designated as 'NEIN' — a localized gravitational dampener capable of temporarily freezing the physical parameters of an area to absolute zero, halting even spatial displacement.\n\nCommander Cross led the vanguard assault personally. Gamma squad suffered 60% equipment degradation due to the intense reality-tears within the sub-sectors, but the Singularity core was successfully extracted. This core now powers the primary defensive grid of our main branch, allowing TBCW safehouses to functionally drop off the Eye's radar during sweeps."
    },
    {
        id: "DRIVE-03_RUINS_EXPEDITION",
        title: "Beyond the Walls: Outskirts Patrol",
        content: "FIELD RECONNAISSANCE LOG // OPERATIVE: VANGUARD INTEL // LOCATION: RUINS PERIMETER.\n\nTo normal denizens of the City, the Outskirts are a myth or a death sentence. To the TBCW Vanguard, they are our back garden and our ultimate fallback point. This log details the long-range scouting mission pushed 50 kilometers beyond the great northern walls.\n\nThe environment outside the Head's jurisdiction is deeply hostile to logical geometry. The sky shifts colors based on localized cognitive pressure, and the terrain consists of calcified technological strata from fallen civilizations that predated the current City configuration.\n\nWe established two underground listening posts near the old rail network lines. During the deployment, we witnessed a migration of 'Eldritch Whales' floating high above the cloud layer, their bodies emitting high-frequency sensory static that temporarily short-circuited our cybernetic augmentations. More concerningly, we noted an increased frequency of Hana Association Grade 1 scouts patrolling the wall edges. The Head is searching for something that escaped during the Library's departure. We must ensure our hidden outposts remain deeply buried beneath the ash fields, or the Claws will cleanse our entire organization to maintain the City's absolute isolation."
    }
];